version: "3.8"


services: 
    app:
        container_name: modelsummarization
        build: .
        command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
        ports: 
            - 2323:8000
        volumes: 
            - .:/app
        restart: always


